FROM node:latest AS build
ARG APP
RUN apt-get update && apt-get install -y --no-install-recommends dumb-init
WORKDIR /app
COPY package*.json /app/
COPY . .
RUN yarn install
RUN yarn nx build $APP


FROM nginx:1.21.0-alpine as production
ARG APP
ENV NODE_ENV production
COPY --from=build /app/dist/apps/${APP} /usr/share/nginx/html
COPY dockerfiles/nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]

